
package com.baeldung.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeService", targetNamespace = "http://service.baeldung.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.baeldung.client.Employee
     * @throws EmployeeNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.GetEmployeeResponse")
    @Action(input = "http://service.baeldung.com/EmployeeService/getEmployeeRequest", output = "http://service.baeldung.com/EmployeeService/getEmployeeResponse", fault = {
        @FaultAction(className = EmployeeNotFound_Exception.class, value = "http://service.baeldung.com/EmployeeService/getEmployee/Fault/EmployeeNotFound")
    })
    public Employee getEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws EmployeeNotFound_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.baeldung.client.Employee
     * @throws EmployeeNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.UpdateEmployeeResponse")
    @Action(input = "http://service.baeldung.com/EmployeeService/updateEmployeeRequest", output = "http://service.baeldung.com/EmployeeService/updateEmployeeResponse", fault = {
        @FaultAction(className = EmployeeNotFound_Exception.class, value = "http://service.baeldung.com/EmployeeService/updateEmployee/Fault/EmployeeNotFound")
    })
    public Employee updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws EmployeeNotFound_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws EmployeeNotFound_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.DeleteEmployeeResponse")
    @Action(input = "http://service.baeldung.com/EmployeeService/deleteEmployeeRequest", output = "http://service.baeldung.com/EmployeeService/deleteEmployeeResponse", fault = {
        @FaultAction(className = EmployeeNotFound_Exception.class, value = "http://service.baeldung.com/EmployeeService/deleteEmployee/Fault/EmployeeNotFound")
    })
    public boolean deleteEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws EmployeeNotFound_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.baeldung.client.Employee
     * @throws EmployeeAlreadyExists_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.AddEmployeeResponse")
    @Action(input = "http://service.baeldung.com/EmployeeService/addEmployeeRequest", output = "http://service.baeldung.com/EmployeeService/addEmployeeResponse", fault = {
        @FaultAction(className = EmployeeAlreadyExists_Exception.class, value = "http://service.baeldung.com/EmployeeService/addEmployee/Fault/EmployeeAlreadyExists")
    })
    public Employee addEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws EmployeeAlreadyExists_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countEmployees", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.CountEmployees")
    @ResponseWrapper(localName = "countEmployeesResponse", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.CountEmployeesResponse")
    @Action(input = "http://service.baeldung.com/EmployeeService/countEmployeesRequest", output = "http://service.baeldung.com/EmployeeService/countEmployeesResponse")
    public int countEmployees();

    /**
     * 
     * @return
     *     returns java.util.List<com.baeldung.client.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://service.baeldung.com/", className = "com.baeldung.client.GetAllEmployeesResponse")
    @Action(input = "http://service.baeldung.com/EmployeeService/getAllEmployeesRequest", output = "http://service.baeldung.com/EmployeeService/getAllEmployeesResponse")
    public List<Employee> getAllEmployees();

}
